services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: avantime
      POSTGRES_USER: avantime
      POSTGRES_PASSWORD: avantime
    ports:
      - "5432:5432"
    volumes:
      - avantime_postgres_data:/var/lib/postgresql/data

volumes:
  avantime_postgres_data:
