/* eslint-disable @typescript-eslint/no-explicit-any */
import { getPrisma } from '@avantime/database';
import { recordSystemEvent } from './system-events';
export type EmailTemplate='REQUEST_CREATED'|'REQUEST_UPDATED'|'NEW_MESSAGE'|'PASSWORD_RESET'|'SLA_ALERT'|'WEEKLY_SUMMARY';
export type EmailQueueItem={id:string;recipient:string;subject:string;template:string;status:'PENDING'|'SENDING'|'SENT'|'FAILED';attempts:number;lastError?:string|null;createdAt:string;sentAt?:string|null};
const demo:EmailQueueItem[]=[];
export function renderEmail(template:EmailTemplate,v:Record<string,string>){const id=v.requestId??'',title=v.title??'',url=v.url??'',body=v.body??'';const map:Record<EmailTemplate,[string,string]>={REQUEST_CREATED:[`Обращение ${id} принято`,`Мы приняли обращение «${title}». ${url}`],REQUEST_UPDATED:[`Статус обращения ${id} изменён`,`Новый статус: ${v.status??''}. ${url}`],NEW_MESSAGE:[`Новое сообщение по ${id}`,`По обращению «${title}»: ${body}. ${url}`],PASSWORD_RESET:['Восстановление пароля Avantime',`Откройте ссылку: ${url}`],SLA_ALERT:[`SLA: требуется внимание — ${id}`,`Срок обращения «${title}»: ${v.dueAt??''}. ${url}`],WEEKLY_SUMMARY:['Еженедельная сводка Avantime',body]};const [subject,textBody]=map[template];return{subject,textBody,htmlBody:`<div style="font-family:Arial"><h2>${subject}</h2><p>${textBody}</p><hr><p>Avantime</p></div>`}}
async function deliver(to:string,subject:string,text:string,html?:string){if(process.env.RESEND_API_KEY){const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${process.env.RESEND_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({from:process.env.MAIL_FROM||'Avantime <support@avantime.lv>',to:[to],subject,text,html})});if(!r.ok)throw new Error(`Resend ${r.status}: ${await r.text()}`);const d=await r.json() as {id?:string};return d.id;}console.info(`[MAIL DEMO] ${to} | ${subject} | ${text}`);return `demo-${Date.now()}`;}
export async function enqueueEmail(i:{recipient:string;subject:string;textBody:string;htmlBody?:string;template:EmailTemplate;userId?:string}){if(process.env.DATABASE_URL){try{const prisma=await getPrisma();if(prisma){const row=await prisma.emailMessage.create({data:i});await processEmail(row.id);return row;}}catch(e){console.warn('Cannot persist email',e)}}const row:EmailQueueItem={id:`mail-${Date.now()}`,recipient:i.recipient,subject:i.subject,template:i.template,status:'PENDING',attempts:0,createdAt:new Date().toISOString()};demo.unshift(row);await processEmail(row.id);return row;}
export async function processEmail(id:string){if(process.env.DATABASE_URL){try{const prisma=await getPrisma();if(prisma){const row=await prisma.emailMessage.findUnique({where:{id}});if(!row||row.status==='SENT')return;await prisma.emailMessage.update({where:{id},data:{status:'SENDING',attempts:{increment:1}}});try{const providerId=await deliver(row.recipient,row.subject,row.textBody,row.htmlBody??undefined);await prisma.emailMessage.update({where:{id},data:{status:'SENT',providerId,sentAt:new Date(),lastError:null}});await recordSystemEvent({level:'INFO',category:'EMAIL',message:`Письмо отправлено: ${row.subject}`,actorEmail:row.recipient});}catch(e){await prisma.emailMessage.update({where:{id},data:{status:'FAILED',lastError:e instanceof Error?e.message:'Unknown'}});}return;}}catch(e){console.warn('Cannot process email',e)}}const row=demo.find(x=>x.id===id);if(!row)return;row.attempts++;try{await deliver(row.recipient,row.subject,'Демонстрационное письмо Avantime');row.status='SENT';row.sentAt=new Date().toISOString();}catch(e){row.status='FAILED';row.lastError=e instanceof Error?e.message:'Unknown';}}
export async function listEmailQueue(limit=100):Promise<EmailQueueItem[]>{if(process.env.DATABASE_URL){try{const prisma=await getPrisma();if(prisma){const rows=await prisma.emailMessage.findMany({orderBy:{createdAt:'desc'},take:limit});return rows.map((r:any)=>({...r,createdAt:r.createdAt.toISOString(),sentAt:r.sentAt?.toISOString()??null}));}}catch(e){console.warn('Cannot list email queue',e)}}return demo.slice(0,limit);}
export async function sendTemplatedEmail(recipient:string,template:EmailTemplate,v:Record<string,string>,userId?:string){return enqueueEmail({recipient,template,userId,...renderEmail(template,v)});}
