import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { PageShell } from '../../../components/page-shell';
import { getKnowledgeArticle } from '../../../lib/knowledge-store';

type Props = { params: Promise<{ slug: string }> };
export const dynamic = 'force-dynamic';
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { slug } = await params; const article = await getKnowledgeArticle(slug); return article ? { title: `${article.title} — Avantime`, description: article.summary } : {}; }
export default async function ArticlePage({ params }: Props) { const { slug } = await params; const article = await getKnowledgeArticle(slug); if (!article) notFound(); return <PageShell><article><header className="border-b border-slate-200 bg-slate-50"><div className="mx-auto max-w-4xl px-6 py-20 sm:py-28"><Link href="/knowledge" className="text-sm font-bold text-blue-600">← База знаний</Link><p className="mt-10 text-xs font-black uppercase tracking-[0.18em] text-blue-600">{article.category} · {article.readingTime}</p><h1 className="mt-5 text-4xl font-black leading-tight tracking-[-0.035em] sm:text-6xl">{article.title}</h1><p className="mt-7 text-xl leading-9 text-slate-600">{article.summary}</p><div className="mt-6 flex flex-wrap gap-2">{article.tags.map((tag) => <span key={tag} className="rounded-full bg-white px-3 py-1 text-xs font-bold text-slate-600">{tag}</span>)}</div></div></header><div className="mx-auto max-w-3xl space-y-14 px-6 py-20">{article.sections.map((section) => <section key={section.title}><h2 className="text-3xl font-black tracking-tight">{section.title}</h2><div className="mt-6 space-y-5">{section.paragraphs.map((paragraph) => <p key={paragraph} className="text-lg leading-8 text-slate-700">{paragraph}</p>)}</div></section>)}<div className="rounded-3xl bg-blue-50 p-8"><h2 className="text-2xl font-black">Нужна оценка вашей ситуации?</h2><p className="mt-3 leading-7 text-slate-600">Разберем процесс и предложим практичный первый этап без обязательства начинать большой проект.</p><Link href="/contacts" className="mt-6 inline-flex rounded-full bg-blue-600 px-6 py-3 font-black text-white">Обсудить задачу</Link></div></div></article></PageShell>; }
